import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:budget_app/constants/app_assets.dart';
import 'package:budget_app/models_Like_Skins_and_lessons_templates/avatar_skin.dart';
import 'package:budget_app/models_Like_Skins_and_lessons_templates/tutorial_steps.dart';
import 'package:budget_app/widgets_custom_lotties/mentor_image.dart';

/// The guide turtle wearing the player's skin.
///
/// **The ask:** *"Make the turtle skins change it for the guides and
/// tutorials."*
///
/// **What was there:** four hardcoded PNGs of the classic turtle, used by the
/// tour, the coach marks, the daily tip and the hub tile. A player who had
/// pulled Guild Runner — a 1-in-1,000 legendary — walked the app as an orange
/// turtle and was taught by a green one.
///
/// Art is generated by `tool/make_mentor_skins.py`, which measures the
/// palette out of the skins themselves rather than repeating hex values.
void main() {
  const poses = TutorialMascot.values;

  group('the art', () {
    test('every turtle skin has every pose', () {
      for (final skinId in AppAssets.mentorSkinIds) {
        for (final pose in poses) {
          final path = AppAssets.turtleMentorPose(pose.poseId, skinId);
          expect(
            File(path).existsSync(),
            isTrue,
            reason:
                '$skinId has no ${pose.poseId} pose at $path. '
                'Run: python tool/make_mentor_skins.py',
          );
        }
      }
    });

    test('a skinned pose is never the same file as the classic one', () {
      // The first run of the generator drew the accessory *under* the pose,
      // so the coin-shell guide came out with no coin — byte-identical to
      // classic for two of the four poses. It looked like nothing had
      // happened, because nothing had.
      for (final skinId in AppAssets.mentorSkinIds) {
        for (final pose in poses) {
          final skinned = File(
            AppAssets.turtleMentorPose(pose.poseId, skinId),
          ).readAsBytesSync();
          final classic = File(pose.asset).readAsBytesSync();

          expect(
            skinned,
            isNot(classic),
            reason: '$skinId\'s ${pose.poseId} guide is the classic turtle',
          );
        }
      }
    });

    test('every mentor skin id is a real skin', () {
      // A typo here would fall silently back to the classic turtle forever.
      final ids = budgetBuddySkins.map((skin) => skin.id).toSet();
      for (final skinId in AppAssets.mentorSkinIds) {
        expect(ids, contains(skinId));
      }
    });

    test('the folder ships', () {
      final pubspec = File('pubspec.yaml').readAsStringSync();
      expect(pubspec.contains('assets/own_skins/turtle_mentor/'), isTrue);
    });
  });

  group('resolving a pose', () {
    test('a turtle skin gets its own art', () {
      expect(
        AppAssets.turtleMentorPose('idle', 'guild_runner'),
        endsWith('turtle_mentor_idle_guild_runner.png'),
      );
    });

    test('a villager falls back to the classic guide', () {
      // Deliberate, not an oversight: a villager has no mentor pose to
      // recolour, and inventing one is a different job. What matters is that
      // it resolves to art that exists rather than to a missing file.
      final path = AppAssets.turtleMentorPose('idle', 'villager_classic');
      expect(path, AppAssets.turtleMentorIdle);
      expect(File(path).existsSync(), isTrue);
    });

    test('an unknown skin id still resolves to real art', () {
      final path = AppAssets.turtleMentorPose('wave', 'not_a_skin');
      expect(File(path).existsSync(), isTrue);
    });

    test('every skin in the game resolves to a file that exists', () {
      for (final skin in budgetBuddySkins) {
        for (final pose in poses) {
          final path = pose.assetFor(skin.id);
          expect(
            File(path).existsSync(),
            isTrue,
            reason: '${skin.name} has no ${pose.poseId} guide at $path',
          );
        }
      }
    });
  });

  group('the widget', () {
    testWidgets('it draws the equipped skin', (tester) async {
      await tester.pumpWidget(
        const MaterialApp(
          home: MentorImage(
            pose: TutorialMascot.wave,
            size: 64,
            debugSkinId: 'explorer_turtle',
          ),
        ),
      );

      final image = tester.widget<Image>(find.byType(Image).first);
      expect(
        (image.image as AssetImage).assetName,
        endsWith('turtle_mentor_wave_explorer_turtle.png'),
      );
    });

    testWidgets('with no account in scope it still renders', (tester) async {
      // The tour and the coach marks can build before sign-in completes, and
      // the coach marks are overlays whose ancestry is not guaranteed to
      // include the providers. Onboarding is the worst screen in the app to
      // throw on, because it is the first one.
      await tester.pumpWidget(
        const MaterialApp(
          home: MentorImage(pose: TutorialMascot.idle, size: 64),
        ),
      );

      expect(tester.takeException(), isNull);
      final image = tester.widget<Image>(find.byType(Image).first);
      expect(
        (image.image as AssetImage).assetName,
        AppAssets.turtleMentorIdle,
      );
    });
  });
}
