name: budget_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  http: ^1.6.0
  webview_flutter: ^4.8.0
  boxicons: ^2.1.0
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/web/react_challenge/index.html
