import 'lesson.dart';

const List<LessonUnit> lessonUnits = <LessonUnit>[
  LessonUnit(
    id: 'unit_1',
    title: 'Unit 1: Budgeting',
    subtitle: 'Foundations',
    description:
        'Build the core habits behind budgeting, saving, and planning each dollar with intention.',
    order: 1,
    ageStage: AgeStage.middleSchool,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_1',
        title: 'Introduction to Budgeting',
        unitId: 'unit_1',
        order: 1,
      ),
      Lesson(
        id: 'lesson_2',
        title: 'Understanding Income',
        unitId: 'unit_1',
        order: 2,
        prerequisites: <String>['lesson_1'],
      ),
      Lesson(
        id: 'quiz_1',
        title: 'Quick Quiz',
        unitId: 'unit_1',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_2'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_3',
        title: 'Expenses and Spending',
        unitId: 'unit_1',
        order: 4,
        prerequisites: <String>['quiz_1'],
      ),
      Lesson(
        id: 'lesson_4',
        title: 'Saving Strategies',
        unitId: 'unit_1',
        order: 5,
        prerequisites: <String>['lesson_3'],
      ),
      Lesson(
        id: 'lesson_savings_goal',
        title: 'Setting a Savings Goal',
        unitId: 'unit_1',
        order: 6,
        prerequisites: <String>['lesson_4'],
      ),
      Lesson(
        id: 'lesson_5',
        title: 'Building Your Budget',
        unitId: 'unit_1',
        order: 7,
        prerequisites: <String>['lesson_savings_goal'],
      ),
      Lesson(
        id: 'test_1',
        title: 'Unit Test',
        unitId: 'unit_1',
        order: 8,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_5'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_2',
    title: 'Unit 2: Credit',
    subtitle: 'Borrowing, banking, and growth',
    description:
        'Learn how credit works, how to avoid harmful debt, and how long-term planning creates stability.',
    order: 2,
    ageStage: AgeStage.graduating,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_6',
        title: 'Credit and Debt Management',
        unitId: 'unit_2',
        order: 1,
        prerequisites: <String>['test_1'],
      ),
      Lesson(
        id: 'lesson_7',
        title: 'Introduction to Investing',
        unitId: 'unit_2',
        order: 2,
        prerequisites: <String>['lesson_6'],
      ),
      Lesson(
        id: 'quiz_2',
        title: 'Quick Quiz',
        unitId: 'unit_2',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_7'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_8',
        title: 'Banking and Financial Tools',
        unitId: 'unit_2',
        order: 4,
        prerequisites: <String>['quiz_2'],
      ),
      Lesson(
        id: 'lesson_9',
        title: 'Emergency Planning',
        unitId: 'unit_2',
        order: 5,
        prerequisites: <String>['lesson_8'],
      ),
      Lesson(
        id: 'lesson_10',
        title: 'Long-Term Financial Goals',
        unitId: 'unit_2',
        order: 6,
        prerequisites: <String>['lesson_9'],
      ),
      Lesson(
        id: 'test_2',
        title: 'Unit Test',
        unitId: 'unit_2',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_10'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_3',
    title: 'Unit 3: Saving Systems',
    subtitle: 'Cash flow and account setup',
    description:
        'Set up money systems that make saving easier, smoother, and more automatic.',
    order: 3,
    ageStage: AgeStage.highSchool,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_11',
        title: 'Pay Yourself First',
        unitId: 'unit_3',
        order: 1,
        prerequisites: <String>['test_2'],
      ),
      Lesson(
        id: 'lesson_12',
        title: 'Sinking Funds',
        unitId: 'unit_3',
        order: 2,
        prerequisites: <String>['lesson_11'],
      ),
      Lesson(
        id: 'quiz_3',
        title: 'Quick Quiz',
        unitId: 'unit_3',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_12'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_13',
        title: 'Choosing Savings Accounts',
        unitId: 'unit_3',
        order: 4,
        prerequisites: <String>['quiz_3'],
      ),
      Lesson(
        id: 'lesson_14',
        title: 'Automating Good Habits',
        unitId: 'unit_3',
        order: 5,
        prerequisites: <String>['lesson_13'],
      ),
      Lesson(
        id: 'lesson_15',
        title: 'Preparing for Irregular Costs',
        unitId: 'unit_3',
        order: 6,
        prerequisites: <String>['lesson_14'],
      ),
      Lesson(
        id: 'test_3',
        title: 'Unit Test',
        unitId: 'unit_3',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_15'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_4',
    title: 'Unit 4: Investing Basics',
    subtitle: 'Risk, growth, and strategy',
    description:
        'Learn how investing grows wealth over time and how to manage risk without guessing.',
    order: 4,
    ageStage: AgeStage.adult,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_16',
        title: 'Why People Invest',
        unitId: 'unit_4',
        order: 1,
        prerequisites: <String>['test_3'],
      ),
      Lesson(
        id: 'lesson_17',
        title: 'Risk and Diversification',
        unitId: 'unit_4',
        order: 2,
        prerequisites: <String>['lesson_16'],
      ),
      Lesson(
        id: 'quiz_4',
        title: 'Quick Quiz',
        unitId: 'unit_4',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_17'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_18',
        title: 'Stocks, Bonds, and Funds',
        unitId: 'unit_4',
        order: 4,
        prerequisites: <String>['quiz_4'],
      ),
      Lesson(
        id: 'lesson_19',
        title: 'Compound Growth',
        unitId: 'unit_4',
        order: 5,
        prerequisites: <String>['lesson_18'],
      ),
      Lesson(
        id: 'lesson_20',
        title: 'Long-Term Investor Mindset',
        unitId: 'unit_4',
        order: 6,
        prerequisites: <String>['lesson_19'],
      ),
      Lesson(
        id: 'test_4',
        title: 'Unit Test',
        unitId: 'unit_4',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_20'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_5',
    title: 'Unit 5: Real-World Money Moves',
    subtitle: 'Decision-making and adulthood',
    description:
        'Practice how budgeting, saving, credit, and investing connect in everyday life decisions.',
    order: 5,
    ageStage: AgeStage.graduating,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_21',
        title: 'Reading a Pay Stub',
        unitId: 'unit_5',
        order: 1,
        prerequisites: <String>['test_4'],
      ),
      Lesson(
        id: 'lesson_22',
        title: 'Comparing Job Offers',
        unitId: 'unit_5',
        order: 2,
        prerequisites: <String>['lesson_21'],
      ),
      Lesson(
        id: 'quiz_5',
        title: 'Quick Quiz',
        unitId: 'unit_5',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_22'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_23',
        title: 'Rent, Utilities, and Living Costs',
        unitId: 'unit_5',
        order: 4,
        prerequisites: <String>['quiz_5'],
      ),
      Lesson(
        id: 'lesson_24',
        title: 'Taxes and Withholding',
        unitId: 'unit_5',
        order: 5,
        prerequisites: <String>['lesson_23'],
      ),
      Lesson(
        id: 'lesson_25',
        title: 'Building a Personal Money Plan',
        unitId: 'unit_5',
        order: 6,
        prerequisites: <String>['lesson_24'],
      ),
      Lesson(
        id: 'test_5',
        title: 'Unit Test',
        unitId: 'unit_5',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_25'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_6',
    title: 'Unit 6: Stocks and Trading',
    subtitle: 'Owning a piece of a company',
    description:
        'What a share actually is, how markets move, and why patience beats '
        'reacting. Completing these pays out real gold and starter shares you '
        'can trade on the Market Board.',
    order: 6,
    ageStage: AgeStage.adult,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_26',
        title: 'What a Share Really Is',
        unitId: 'unit_6',
        order: 1,
        prerequisites: <String>['test_5'],
      ),
      Lesson(
        id: 'lesson_27',
        title: 'Why Prices Move',
        unitId: 'unit_6',
        order: 2,
        prerequisites: <String>['lesson_26'],
      ),
      Lesson(
        id: 'quiz_6',
        title: 'Quick Quiz',
        unitId: 'unit_6',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_27'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_28',
        title: 'Risk, Diversification, and Index Funds',
        unitId: 'unit_6',
        order: 4,
        prerequisites: <String>['quiz_6'],
      ),
      Lesson(
        id: 'lesson_29',
        title: 'Orders, Spreads, and Fees',
        unitId: 'unit_6',
        order: 5,
        prerequisites: <String>['lesson_28'],
      ),
      Lesson(
        id: 'lesson_30',
        title: 'Time in the Market',
        unitId: 'unit_6',
        order: 6,
        prerequisites: <String>['lesson_29'],
      ),
      Lesson(
        id: 'test_6',
        title: 'Unit Test',
        unitId: 'unit_6',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_30'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_7',
    title: 'Unit 7: Spending Traps',
    subtitle: 'Spotting the tricks aimed at you',
    description:
        'Ads, in-game shops, hype and scams are all designed by adults to '
        'separate you from your money. This unit teaches you to see them '
        'coming — the earliest money skill worth having.',
    order: 7,
    ageStage: AgeStage.middleSchool,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_31',
        title: 'Wants Wearing a Needs Costume',
        unitId: 'unit_7',
        order: 1,
        prerequisites: <String>['test_6'],
      ),
      Lesson(
        id: 'lesson_32',
        title: 'How Ads Are Aimed at You',
        unitId: 'unit_7',
        order: 2,
        prerequisites: <String>['lesson_31'],
      ),
      Lesson(
        id: 'quiz_7',
        title: 'Quick Quiz',
        unitId: 'unit_7',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_32'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_33',
        title: 'In-Game Money Is Still Money',
        unitId: 'unit_7',
        order: 4,
        prerequisites: <String>['quiz_7'],
      ),
      Lesson(
        id: 'lesson_34',
        title: 'The 24-Hour Rule',
        unitId: 'unit_7',
        order: 5,
        prerequisites: <String>['lesson_33'],
      ),
      Lesson(
        id: 'lesson_35',
        title: 'Scams, Free Gifts and Too-Good Deals',
        unitId: 'unit_7',
        order: 6,
        prerequisites: <String>['lesson_34'],
      ),
      Lesson(
        id: 'test_7',
        title: 'Unit Test',
        unitId: 'unit_7',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_35'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_8',
    title: 'Unit 8: Money by the Numbers',
    subtitle: 'Reading data without being fooled by it',
    description:
        'Percentages, averages, and charts decide how money decisions get '
        'argued. Learn to read them properly — and to notice when a graph is '
        'quietly lying to you.',
    order: 8,
    ageStage: AgeStage.highSchool,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_36',
        title: 'Percentages You Actually Use',
        unitId: 'unit_8',
        order: 1,
        prerequisites: <String>['test_7'],
      ),
      Lesson(
        id: 'lesson_37',
        title: 'Average vs Median',
        unitId: 'unit_8',
        order: 2,
        prerequisites: <String>['lesson_36'],
      ),
      Lesson(
        id: 'quiz_8',
        title: 'Quick Quiz',
        unitId: 'unit_8',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_37'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_38',
        title: 'Reading a Price Chart',
        unitId: 'unit_8',
        order: 4,
        prerequisites: <String>['quiz_8'],
      ),
      Lesson(
        id: 'lesson_39',
        title: 'How Charts Mislead',
        unitId: 'unit_8',
        order: 5,
        prerequisites: <String>['lesson_38'],
      ),
      Lesson(
        id: 'lesson_40',
        title: 'Tracking Your Own Spending Data',
        unitId: 'unit_8',
        order: 6,
        prerequisites: <String>['lesson_39'],
      ),
      Lesson(
        id: 'test_8',
        title: 'Unit Test',
        unitId: 'unit_8',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_40'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_9',
    title: 'Unit 9: Retirement and the 401(k)',
    subtitle: 'The account you open decades before you need it',
    description:
        'Employer matches, Roth vs traditional, and why starting at 22 beats '
        'starting at 40 by a margin that looks like a typo. Written for '
        'adults, but worth reading early.',
    order: 9,
    ageStage: AgeStage.adult,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_41',
        title: 'Why Retirement Accounts Exist',
        unitId: 'unit_9',
        order: 1,
        prerequisites: <String>['test_8'],
      ),
      Lesson(
        id: 'lesson_42',
        title: 'The Employer Match',
        unitId: 'unit_9',
        order: 2,
        prerequisites: <String>['lesson_41'],
      ),
      Lesson(
        id: 'quiz_9',
        title: 'Quick Quiz',
        unitId: 'unit_9',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_42'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_43',
        title: 'Roth vs Traditional',
        unitId: 'unit_9',
        order: 4,
        prerequisites: <String>['quiz_9'],
      ),
      Lesson(
        id: 'lesson_44',
        title: 'Starting Early Beats Saving More',
        unitId: 'unit_9',
        order: 5,
        prerequisites: <String>['lesson_43'],
      ),
      Lesson(
        id: 'lesson_45',
        title: 'Fees, Vesting and Job Changes',
        unitId: 'unit_9',
        order: 6,
        prerequisites: <String>['lesson_44'],
      ),
      Lesson(
        id: 'test_9',
        title: 'Unit Test',
        unitId: 'unit_9',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_45'],
        estimatedMinutes: 6,
      ),
    ],
  ),
];
