import 'lesson.dart';

const List<LessonUnit> lessonUnits = <LessonUnit>[
  LessonUnit(
    id: 'unit_1',
    title: 'Unit 1: Budgeting',
    subtitle: 'Foundations',
    description:
        'Build the core habits behind budgeting, saving, and planning each dollar with intention.',
    order: 1,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_1',
        title: 'Introduction to Budgeting',
        unitId: 'unit_1',
        order: 1,
      ),
      Lesson(
        id: 'lesson_2',
        title: 'Understanding Income',
        unitId: 'unit_1',
        order: 2,
        prerequisites: <String>['lesson_1'],
      ),
      Lesson(
        id: 'quiz_1',
        title: 'Quick Quiz',
        unitId: 'unit_1',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_2'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_3',
        title: 'Expenses and Spending',
        unitId: 'unit_1',
        order: 4,
        prerequisites: <String>['quiz_1'],
      ),
      Lesson(
        id: 'lesson_4',
        title: 'Saving Strategies',
        unitId: 'unit_1',
        order: 5,
        prerequisites: <String>['lesson_3'],
      ),
      Lesson(
        id: 'lesson_5',
        title: 'Building Your Budget',
        unitId: 'unit_1',
        order: 6,
        prerequisites: <String>['lesson_4'],
      ),
      Lesson(
        id: 'test_1',
        title: 'Unit Test',
        unitId: 'unit_1',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_5'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_2',
    title: 'Unit 2: Credit',
    subtitle: 'Borrowing, banking, and growth',
    description:
        'Learn how credit works, how to avoid harmful debt, and how long-term planning creates stability.',
    order: 2,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_6',
        title: 'Credit and Debt Management',
        unitId: 'unit_2',
        order: 1,
        prerequisites: <String>['test_1'],
      ),
      Lesson(
        id: 'lesson_7',
        title: 'Introduction to Investing',
        unitId: 'unit_2',
        order: 2,
        prerequisites: <String>['lesson_6'],
      ),
      Lesson(
        id: 'quiz_2',
        title: 'Quick Quiz',
        unitId: 'unit_2',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_7'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_8',
        title: 'Banking and Financial Tools',
        unitId: 'unit_2',
        order: 4,
        prerequisites: <String>['quiz_2'],
      ),
      Lesson(
        id: 'lesson_9',
        title: 'Emergency Planning',
        unitId: 'unit_2',
        order: 5,
        prerequisites: <String>['lesson_8'],
      ),
      Lesson(
        id: 'lesson_10',
        title: 'Long-Term Financial Goals',
        unitId: 'unit_2',
        order: 6,
        prerequisites: <String>['lesson_9'],
      ),
      Lesson(
        id: 'test_2',
        title: 'Unit Test',
        unitId: 'unit_2',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_10'],
        estimatedMinutes: 6,
      ),
    ],
  ),
];
