import 'lesson.dart';

const List<LessonUnit> lessonUnits = <LessonUnit>[
  LessonUnit(
    id: 'unit_1',
    title: 'Unit 1: Budgeting',
    subtitle: 'Foundations',
    description:
        'Build the core habits behind budgeting, saving, and planning each dollar with intention.',
    order: 1,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_1',
        title: 'Introduction to Budgeting',
        unitId: 'unit_1',
        order: 1,
      ),
      Lesson(
        id: 'lesson_2',
        title: 'Understanding Income',
        unitId: 'unit_1',
        order: 2,
        prerequisites: <String>['lesson_1'],
      ),
      Lesson(
        id: 'quiz_1',
        title: 'Quick Quiz',
        unitId: 'unit_1',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_2'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_3',
        title: 'Expenses and Spending',
        unitId: 'unit_1',
        order: 4,
        prerequisites: <String>['quiz_1'],
      ),
      Lesson(
        id: 'lesson_4',
        title: 'Saving Strategies',
        unitId: 'unit_1',
        order: 5,
        prerequisites: <String>['lesson_3'],
      ),
      Lesson(
        id: 'lesson_5',
        title: 'Building Your Budget',
        unitId: 'unit_1',
        order: 6,
        prerequisites: <String>['lesson_4'],
      ),
      Lesson(
        id: 'test_1',
        title: 'Unit Test',
        unitId: 'unit_1',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_5'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_2',
    title: 'Unit 2: Credit',
    subtitle: 'Borrowing, banking, and growth',
    description:
        'Learn how credit works, how to avoid harmful debt, and how long-term planning creates stability.',
    order: 2,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_6',
        title: 'Credit and Debt Management',
        unitId: 'unit_2',
        order: 1,
        prerequisites: <String>['test_1'],
      ),
      Lesson(
        id: 'lesson_7',
        title: 'Introduction to Investing',
        unitId: 'unit_2',
        order: 2,
        prerequisites: <String>['lesson_6'],
      ),
      Lesson(
        id: 'quiz_2',
        title: 'Quick Quiz',
        unitId: 'unit_2',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_7'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_8',
        title: 'Banking and Financial Tools',
        unitId: 'unit_2',
        order: 4,
        prerequisites: <String>['quiz_2'],
      ),
      Lesson(
        id: 'lesson_9',
        title: 'Emergency Planning',
        unitId: 'unit_2',
        order: 5,
        prerequisites: <String>['lesson_8'],
      ),
      Lesson(
        id: 'lesson_10',
        title: 'Long-Term Financial Goals',
        unitId: 'unit_2',
        order: 6,
        prerequisites: <String>['lesson_9'],
      ),
      Lesson(
        id: 'test_2',
        title: 'Unit Test',
        unitId: 'unit_2',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_10'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_3',
    title: 'Unit 3: Saving Systems',
    subtitle: 'Cash flow and account setup',
    description:
        'Set up money systems that make saving easier, smoother, and more automatic.',
    order: 3,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_11',
        title: 'Pay Yourself First',
        unitId: 'unit_3',
        order: 1,
        prerequisites: <String>['test_2'],
      ),
      Lesson(
        id: 'lesson_12',
        title: 'Sinking Funds',
        unitId: 'unit_3',
        order: 2,
        prerequisites: <String>['lesson_11'],
      ),
      Lesson(
        id: 'quiz_3',
        title: 'Quick Quiz',
        unitId: 'unit_3',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_12'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_13',
        title: 'Choosing Savings Accounts',
        unitId: 'unit_3',
        order: 4,
        prerequisites: <String>['quiz_3'],
      ),
      Lesson(
        id: 'lesson_14',
        title: 'Automating Good Habits',
        unitId: 'unit_3',
        order: 5,
        prerequisites: <String>['lesson_13'],
      ),
      Lesson(
        id: 'lesson_15',
        title: 'Preparing for Irregular Costs',
        unitId: 'unit_3',
        order: 6,
        prerequisites: <String>['lesson_14'],
      ),
      Lesson(
        id: 'test_3',
        title: 'Unit Test',
        unitId: 'unit_3',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_15'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_4',
    title: 'Unit 4: Investing Basics',
    subtitle: 'Risk, growth, and strategy',
    description:
        'Learn how investing grows wealth over time and how to manage risk without guessing.',
    order: 4,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_16',
        title: 'Why People Invest',
        unitId: 'unit_4',
        order: 1,
        prerequisites: <String>['test_3'],
      ),
      Lesson(
        id: 'lesson_17',
        title: 'Risk and Diversification',
        unitId: 'unit_4',
        order: 2,
        prerequisites: <String>['lesson_16'],
      ),
      Lesson(
        id: 'quiz_4',
        title: 'Quick Quiz',
        unitId: 'unit_4',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_17'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_18',
        title: 'Stocks, Bonds, and Funds',
        unitId: 'unit_4',
        order: 4,
        prerequisites: <String>['quiz_4'],
      ),
      Lesson(
        id: 'lesson_19',
        title: 'Compound Growth',
        unitId: 'unit_4',
        order: 5,
        prerequisites: <String>['lesson_18'],
      ),
      Lesson(
        id: 'lesson_20',
        title: 'Long-Term Investor Mindset',
        unitId: 'unit_4',
        order: 6,
        prerequisites: <String>['lesson_19'],
      ),
      Lesson(
        id: 'test_4',
        title: 'Unit Test',
        unitId: 'unit_4',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_20'],
        estimatedMinutes: 6,
      ),
    ],
  ),
  LessonUnit(
    id: 'unit_5',
    title: 'Unit 5: Real-World Money Moves',
    subtitle: 'Decision-making and adulthood',
    description:
        'Practice how budgeting, saving, credit, and investing connect in everyday life decisions.',
    order: 5,
    lessons: <Lesson>[
      Lesson(
        id: 'lesson_21',
        title: 'Reading a Pay Stub',
        unitId: 'unit_5',
        order: 1,
        prerequisites: <String>['test_4'],
      ),
      Lesson(
        id: 'lesson_22',
        title: 'Comparing Job Offers',
        unitId: 'unit_5',
        order: 2,
        prerequisites: <String>['lesson_21'],
      ),
      Lesson(
        id: 'quiz_5',
        title: 'Quick Quiz',
        unitId: 'unit_5',
        order: 3,
        type: LessonNodeType.quiz,
        prerequisites: <String>['lesson_22'],
        estimatedMinutes: 4,
      ),
      Lesson(
        id: 'lesson_23',
        title: 'Rent, Utilities, and Living Costs',
        unitId: 'unit_5',
        order: 4,
        prerequisites: <String>['quiz_5'],
      ),
      Lesson(
        id: 'lesson_24',
        title: 'Taxes and Withholding',
        unitId: 'unit_5',
        order: 5,
        prerequisites: <String>['lesson_23'],
      ),
      Lesson(
        id: 'lesson_25',
        title: 'Building a Personal Money Plan',
        unitId: 'unit_5',
        order: 6,
        prerequisites: <String>['lesson_24'],
      ),
      Lesson(
        id: 'test_5',
        title: 'Unit Test',
        unitId: 'unit_5',
        order: 7,
        type: LessonNodeType.unitTest,
        prerequisites: <String>['lesson_25'],
        estimatedMinutes: 6,
      ),
    ],
  ),
];
